// Code generated by the Encore v1.53.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-everydle-qnxi.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the everydle-qnxi Encore application.
 */
export default class Client {
    public readonly chests: chests.ServiceClient
    public readonly daily: daily.ServiceClient
    public readonly friendship: friendship.ServiceClient
    public readonly gamestate: gamestate.ServiceClient
    public readonly inventory: inventory.ServiceClient
    public readonly match: match.ServiceClient
    public readonly notifications: notifications.ServiceClient
    public readonly progress: progress.ServiceClient
    public readonly stars: stars.ServiceClient
    public readonly trophies: trophies.ServiceClient
    public readonly user: user.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.chests = new chests.ServiceClient(base)
        this.daily = new daily.ServiceClient(base)
        this.friendship = new friendship.ServiceClient(base)
        this.gamestate = new gamestate.ServiceClient(base)
        this.inventory = new inventory.ServiceClient(base)
        this.match = new match.ServiceClient(base)
        this.notifications = new notifications.ServiceClient(base)
        this.progress = new progress.ServiceClient(base)
        this.stars = new stars.ServiceClient(base)
        this.trophies = new trophies.ServiceClient(base)
        this.user = new user.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

export namespace chests {
    export interface ChestReward {
        type: "coins" | "hint"
        amount: number
    }

    export interface ClaimChestRequest {
        userId: string
        date: string
        milestone: number
        rewardType: "coins" | "hint"
        rewardAmount: number
    }

    export interface ClaimChestResponse {
        success: boolean
        claimedMilestones?: number[]
        reward?: ChestReward
        error?: string
    }

    export interface GetClaimedChestsResponse {
        success: boolean
        claimedMilestones?: number[]
        error?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.claimChest = this.claimChest.bind(this)
            this.getClaimedChests = this.getClaimedChests.bind(this)
        }

        /**
         * Claim a chest
         */
        public async claimChest(params: ClaimChestRequest): Promise<ClaimChestResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/chests/claim`, JSON.stringify(params))
            return await resp.json() as ClaimChestResponse
        }

        /**
         * Get claimed chests for a specific date
         */
        public async getClaimedChests(userId: string, date: string): Promise<GetClaimedChestsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/chests/claimed/${encodeURIComponent(userId)}/${encodeURIComponent(date)}`)
            return await resp.json() as GetClaimedChestsResponse
        }
    }
}

export namespace daily {
    export interface CompletedGame {
        "game_id"?: string
        "game_number": number
        "completion_date"?: string
        "completed_at": string
    }

    export interface DailyGameCompletion {
        id: string
        "user_id": string
        "game_id": string
        "game_number": number
        "completion_date": string
        "completed_at": string
    }

    export interface GetAllCompletedGamesRequest {
        limit?: number
        offset?: number
    }

    export interface GetAllCompletedGamesResponse {
        success: boolean
        games?: CompletedGame[]
        error?: string
    }

    export interface GetCompletedGamesForDateRequest {
        date?: string
    }

    export interface GetCompletedGamesForDateResponse {
        success: boolean
        games?: CompletedGame[]
        error?: string
    }

    export interface IsGameCompletedResponse {
        success: boolean
        completed?: boolean
        completedAt?: string | null
        error?: string
    }

    export interface MarkDailyGameCompletedRequest {
        userId: string
        gameId: string
        gameNumber: number
        completionDate?: string
    }

    export interface MarkDailyGameCompletedResponse {
        success: boolean
        completion?: DailyGameCompletion
        alreadyCompleted?: boolean
        error?: string
    }

    export interface UnmarkDailyGameCompletedRequest {
        userId: string
        gameId: string
        gameNumber: number
    }

    export interface UnmarkDailyGameCompletedResponse {
        success: boolean
        error?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getAllCompletedGames = this.getAllCompletedGames.bind(this)
            this.getCompletedGamesForDate = this.getCompletedGamesForDate.bind(this)
            this.isGameCompleted = this.isGameCompleted.bind(this)
            this.markDailyGameCompleted = this.markDailyGameCompleted.bind(this)
            this.unmarkDailyGameCompleted = this.unmarkDailyGameCompleted.bind(this)
        }

        /**
         * Get all completed games for a game type
         */
        public async getAllCompletedGames(userId: string, gameId: string, params: GetAllCompletedGamesRequest): Promise<GetAllCompletedGamesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/daily/all/${encodeURIComponent(userId)}/${encodeURIComponent(gameId)}`, undefined, {query})
            return await resp.json() as GetAllCompletedGamesResponse
        }

        /**
         * Get completed games for a specific date
         */
        public async getCompletedGamesForDate(userId: string, params: GetCompletedGamesForDateRequest): Promise<GetCompletedGamesForDateResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                date: params.date,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/daily/date/${encodeURIComponent(userId)}`, undefined, {query})
            return await resp.json() as GetCompletedGamesForDateResponse
        }

        /**
         * Check if a game is completed
         */
        public async isGameCompleted(userId: string, gameId: string, gameNumber: number): Promise<IsGameCompletedResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/daily/check/${encodeURIComponent(userId)}/${encodeURIComponent(gameId)}/${encodeURIComponent(gameNumber)}`)
            return await resp.json() as IsGameCompletedResponse
        }

        /**
         * Mark a daily game as completed
         */
        public async markDailyGameCompleted(params: MarkDailyGameCompletedRequest): Promise<MarkDailyGameCompletedResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/daily/complete`, JSON.stringify(params))
            return await resp.json() as MarkDailyGameCompletedResponse
        }

        /**
         * Unmark a daily game completion
         */
        public async unmarkDailyGameCompleted(params: UnmarkDailyGameCompletedRequest): Promise<UnmarkDailyGameCompletedResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                gameId:     params.gameId,
                gameNumber: String(params.gameNumber),
                userId:     params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/daily/uncomplete`, undefined, {query})
            return await resp.json() as UnmarkDailyGameCompletedResponse
        }
    }
}

export namespace friendship {
    export interface AcceptFriendRequestRequest {
        userId: string
        friendId: string
    }

    export interface AcceptFriendRequestResponse {
        success: boolean
        friendship?: Friendship
        error?: string
    }

    export interface BlockUserRequest {
        userId: string
        blockedId: string
    }

    export interface BlockUserResponse {
        success: boolean
        error?: string
    }

    export interface FriendUser {
        id: string
        "firebase_id": string
        name: string | null
        username: string | null
        avatar: string | null
        "created_at": string
        "friendship_created_at"?: string
        "requested_at"?: string
        "sent_at"?: string
        "request_id"?: string
        status?: string
    }

    export interface Friendship {
        id: string
        "user_id": string
        "friend_id": string
        status: string
        "created_at": string
    }

    export type FriendshipStatus = "none" | "friends" | "request_sent" | "request_received" | "blocked_by_me" | "blocked_by_them" | "rejected_by_me" | "rejected_by_them"

    export interface GetFriendsRequest {
        limit?: number
        offset?: number
    }

    export interface GetFriendsResponse {
        success: boolean
        friends?: FriendUser[]
        error?: string
    }

    export interface GetFriendshipStatusResponse {
        success: boolean
        status?: FriendshipStatus
        myStatus?: string | null
        theirStatus?: string | null
        error?: string
    }

    export interface GetPendingRequestsRequest {
        limit?: number
        offset?: number
    }

    export interface GetPendingRequestsResponse {
        success: boolean
        requests?: FriendUser[]
        error?: string
    }

    export interface GetSentRequestsRequest {
        limit?: number
        offset?: number
    }

    export interface GetSentRequestsResponse {
        success: boolean
        requests?: FriendUser[]
        error?: string
    }

    export interface RejectFriendRequestRequest {
        userId: string
        friendId: string
    }

    export interface RejectFriendRequestResponse {
        success: boolean
        error?: string
    }

    export interface RemoveFriendRequest {
        userId: string
        friendId: string
    }

    export interface RemoveFriendResponse {
        success: boolean
        error?: string
    }

    export interface SendFriendRequestRequest {
        userId: string
        friendId: string
        isInvitation?: boolean
    }

    export interface SendFriendRequestResponse {
        success: boolean
        friendship?: Friendship
        autoAccepted?: boolean
        error?: string
    }

    export interface UnblockUserRequest {
        userId: string
        blockedId: string
    }

    export interface UnblockUserResponse {
        success: boolean
        error?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.acceptFriendRequest = this.acceptFriendRequest.bind(this)
            this.blockUser = this.blockUser.bind(this)
            this.getFriends = this.getFriends.bind(this)
            this.getFriendshipStatus = this.getFriendshipStatus.bind(this)
            this.getPendingRequests = this.getPendingRequests.bind(this)
            this.getSentRequests = this.getSentRequests.bind(this)
            this.rejectFriendRequest = this.rejectFriendRequest.bind(this)
            this.removeFriend = this.removeFriend.bind(this)
            this.sendFriendRequest = this.sendFriendRequest.bind(this)
            this.unblockUser = this.unblockUser.bind(this)
        }

        /**
         * Accept a friend request
         */
        public async acceptFriendRequest(params: AcceptFriendRequestRequest): Promise<AcceptFriendRequestResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/friendship/accept`, JSON.stringify(params))
            return await resp.json() as AcceptFriendRequestResponse
        }

        /**
         * Block a user
         */
        public async blockUser(params: BlockUserRequest): Promise<BlockUserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/friendship/block`, JSON.stringify(params))
            return await resp.json() as BlockUserResponse
        }

        /**
         * Get friends list
         */
        public async getFriends(userId: string, params: GetFriendsRequest): Promise<GetFriendsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/friendship/friends/${encodeURIComponent(userId)}`, undefined, {query})
            return await resp.json() as GetFriendsResponse
        }

        /**
         * Get friendship status between two users
         */
        public async getFriendshipStatus(userId: string, otherId: string): Promise<GetFriendshipStatusResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/friendship/status/${encodeURIComponent(userId)}/${encodeURIComponent(otherId)}`)
            return await resp.json() as GetFriendshipStatusResponse
        }

        /**
         * Get pending friend requests (received)
         */
        public async getPendingRequests(userId: string, params: GetPendingRequestsRequest): Promise<GetPendingRequestsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/friendship/pending/${encodeURIComponent(userId)}`, undefined, {query})
            return await resp.json() as GetPendingRequestsResponse
        }

        /**
         * Get sent friend requests
         */
        public async getSentRequests(userId: string, params: GetSentRequestsRequest): Promise<GetSentRequestsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/friendship/sent/${encodeURIComponent(userId)}`, undefined, {query})
            return await resp.json() as GetSentRequestsResponse
        }

        /**
         * Reject a friend request
         */
        public async rejectFriendRequest(params: RejectFriendRequestRequest): Promise<RejectFriendRequestResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/friendship/reject`, JSON.stringify(params))
            return await resp.json() as RejectFriendRequestResponse
        }

        /**
         * Remove a friend
         */
        public async removeFriend(params: RemoveFriendRequest): Promise<RemoveFriendResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                friendId: params.friendId,
                userId:   params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/friendship/remove`, undefined, {query})
            return await resp.json() as RemoveFriendResponse
        }

        /**
         * Send a friend request
         */
        public async sendFriendRequest(params: SendFriendRequestRequest): Promise<SendFriendRequestResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/friendship/request`, JSON.stringify(params))
            return await resp.json() as SendFriendRequestResponse
        }

        /**
         * Unblock a user
         */
        public async unblockUser(params: UnblockUserRequest): Promise<UnblockUserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/friendship/unblock`, JSON.stringify(params))
            return await resp.json() as UnblockUserResponse
        }
    }
}

export namespace gamestate {
    export interface DeleteGameStateResponse {
        success: boolean
        error?: string
    }

    export interface GameHistoryEntry {
        "game_number": number
        state: { [key: string]: any }
        "is_completed": boolean
        "is_won": boolean | null
        "created_at": string
        "updated_at": string
    }

    export interface GameSaveState {
        id: string
        "user_id": string
        "game_id": string
        "game_number": number
        state: { [key: string]: any }
        "is_completed": boolean
        "is_won": boolean | null
        "created_at": string
        "updated_at": string
    }

    export interface GetGameHistoryRequest {
        limit?: number
        offset?: number
    }

    export interface GetGameHistoryResponse {
        success: boolean
        history?: GameHistoryEntry[]
        error?: string
    }

    export interface GetGameStateResponse {
        success: boolean
        data?: GameSaveState | null
        error?: string
    }

    export interface SaveGameStateRequest {
        userId: string
        gameId: string
        gameNumber: number
        state: { [key: string]: any }
        isCompleted?: boolean
        isWon?: boolean
    }

    export interface SaveGameStateResponse {
        success: boolean
        data?: GameSaveState
        error?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteGameState = this.deleteGameState.bind(this)
            this.getGameHistory = this.getGameHistory.bind(this)
            this.getGameState = this.getGameState.bind(this)
            this.saveGameState = this.saveGameState.bind(this)
        }

        /**
         * Delete game state (reset)
         */
        public async deleteGameState(userId: string, gameId: string, gameNumber: number): Promise<DeleteGameStateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/gamestate/${encodeURIComponent(userId)}/${encodeURIComponent(gameId)}/${encodeURIComponent(gameNumber)}`)
            return await resp.json() as DeleteGameStateResponse
        }

        /**
         * Get game history
         */
        public async getGameHistory(userId: string, gameId: string, params: GetGameHistoryRequest): Promise<GetGameHistoryResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/gamestate/history/${encodeURIComponent(userId)}/${encodeURIComponent(gameId)}`, undefined, {query})
            return await resp.json() as GetGameHistoryResponse
        }

        /**
         * Get game state
         */
        public async getGameState(userId: string, gameId: string, gameNumber: number): Promise<GetGameStateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/gamestate/${encodeURIComponent(userId)}/${encodeURIComponent(gameId)}/${encodeURIComponent(gameNumber)}`)
            return await resp.json() as GetGameStateResponse
        }

        /**
         * Save game state
         */
        public async saveGameState(params: SaveGameStateRequest): Promise<SaveGameStateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/gamestate/save`, JSON.stringify(params))
            return await resp.json() as SaveGameStateResponse
        }
    }
}

export namespace inventory {
    export interface AddGiveupsRequest {
        userId: string
        amount: number
    }

    export interface AddGiveupsResponse {
        success: boolean
        data?: UserInventory
        error?: string
    }

    export interface AddHintsRequest {
        userId: string
        amount: number
    }

    export interface AddHintsResponse {
        success: boolean
        data?: UserInventory
        error?: string
    }

    export interface GetUserInventoryResponse {
        success: boolean
        data?: UserInventory
        error?: string
    }

    export interface UseGiveupRequest {
        userId: string
    }

    export interface UseGiveupResponse {
        success: boolean
        data?: UserInventory
        error?: string
    }

    export interface UseHintRequest {
        userId: string
    }

    export interface UseHintResponse {
        success: boolean
        data?: UserInventory
        error?: string
    }

    export interface UserInventory {
        id: string
        "user_id": string
        hints: number
        giveups: number
        "created_at": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addGiveups = this.addGiveups.bind(this)
            this.addHints = this.addHints.bind(this)
            this.getUserInventory = this.getUserInventory.bind(this)
            this.useGiveup = this.useGiveup.bind(this)
            this.useHint = this.useHint.bind(this)
        }

        /**
         * Add giveups
         */
        public async addGiveups(params: AddGiveupsRequest): Promise<AddGiveupsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/inventory/giveup/add`, JSON.stringify(params))
            return await resp.json() as AddGiveupsResponse
        }

        /**
         * Add hints
         */
        public async addHints(params: AddHintsRequest): Promise<AddHintsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/inventory/hint/add`, JSON.stringify(params))
            return await resp.json() as AddHintsResponse
        }

        /**
         * Get user inventory
         */
        public async getUserInventory(userId: string): Promise<GetUserInventoryResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/inventory/${encodeURIComponent(userId)}`)
            return await resp.json() as GetUserInventoryResponse
        }

        /**
         * Use a giveup
         */
        public async useGiveup(params: UseGiveupRequest): Promise<UseGiveupResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/inventory/giveup/use`, JSON.stringify(params))
            return await resp.json() as UseGiveupResponse
        }

        /**
         * Use a hint
         */
        public async useHint(params: UseHintRequest): Promise<UseHintResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/inventory/hint/use`, JSON.stringify(params))
            return await resp.json() as UseHintResponse
        }
    }
}

export namespace match {
    export interface ApplyBotMatchResultRequest {
        botId: string
        result: MatchResult
        trophyChange?: number
    }

    export interface ApplyBotMatchResultResponse {
        success: boolean
        data?: BotProfile
        trophyChange?: number
        error?: string
    }

    export interface BotProfile {
        id: string
        "bot_name": string
        difficulty: "very_easy" | "easy" | "medium" | "hard"
        trophies: number
        wins: number
        losses: number
        "created_at": string
        "updated_at": string
    }

    export interface GetAllBotsRequest {
        difficulty?: "very_easy" | "easy" | "medium" | "hard"
    }

    export interface GetAllBotsResponse {
        success: boolean
        data?: BotProfile[]
        error?: string
    }

    export interface GetBotProfileResponse {
        success: boolean
        data?: BotProfile
        error?: string
    }

    export interface GetRandomBotRequest {
        difficulty?: "very_easy" | "easy" | "medium" | "hard"
    }

    export interface GetRandomBotResponse {
        success: boolean
        data?: BotProfile
        error?: string
    }

    export interface GetUserMatchHistoryRequest {
        limit?: number
        offset?: number
    }

    export interface GetUserMatchHistoryResponse {
        success: boolean
        data?: MatchLog[]
        error?: string
    }

    export interface LogMatchResultRequest {
        matchId: string
        player1Id: string
        player1Type: "user" | "bot"
        player1Name: string
        player2Id: string
        player2Type: "user" | "bot"
        player2Name: string
        winnerId?: string
        winnerType?: "user" | "bot"
        player1Attempts?: number
        player2Attempts?: number
        player1TimeMs?: number
        player2TimeMs?: number
        player1TrophyChange?: number
        player2TrophyChange?: number
        word: string
        gameType?: string
    }

    export interface LogMatchResultResponse {
        success: boolean
        data?: MatchLog
        error?: string
    }

    export interface MatchLog {
        id: string
        "match_id": string
        "player1_id": string
        "player1_type": "user" | "bot"
        "player1_name": string
        "player2_id": string
        "player2_type": "user" | "bot"
        "player2_name": string
        "winner_id": string | null
        "winner_type": "user" | "bot" | null
        "player1_attempts": number | null
        "player2_attempts": number | null
        "player1_time_ms": number | null
        "player2_time_ms": number | null
        "player1_trophy_change": number
        "player2_trophy_change": number
        word: string
        "game_type": string
        "created_at": string
        result?: "win" | "lose" | "draw"
    }

    export type MatchResult = "win" | "lose"

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.applyBotMatchResult = this.applyBotMatchResult.bind(this)
            this.getAllBots = this.getAllBots.bind(this)
            this.getBotProfile = this.getBotProfile.bind(this)
            this.getRandomBot = this.getRandomBot.bind(this)
            this.getUserMatchHistory = this.getUserMatchHistory.bind(this)
            this.logMatchResult = this.logMatchResult.bind(this)
        }

        /**
         * Apply match result to bot (update trophies, wins, losses)
         */
        public async applyBotMatchResult(params: ApplyBotMatchResultRequest): Promise<ApplyBotMatchResultResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/match/bot/result`, JSON.stringify(params))
            return await resp.json() as ApplyBotMatchResultResponse
        }

        /**
         * Get all bots, optionally filtered by difficulty
         */
        public async getAllBots(params: GetAllBotsRequest): Promise<GetAllBotsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                difficulty: params.difficulty === undefined ? undefined : String(params.difficulty),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/match/bots`, undefined, {query})
            return await resp.json() as GetAllBotsResponse
        }

        /**
         * Get bot profile by ID
         */
        public async getBotProfile(botId: string): Promise<GetBotProfileResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/match/bot/${encodeURIComponent(botId)}`)
            return await resp.json() as GetBotProfileResponse
        }

        /**
         * Get a random bot for matchmaking
         */
        public async getRandomBot(params: GetRandomBotRequest): Promise<GetRandomBotResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                difficulty: params.difficulty === undefined ? undefined : String(params.difficulty),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/match/bot/random`, undefined, {query})
            return await resp.json() as GetRandomBotResponse
        }

        /**
         * Get user match history
         */
        public async getUserMatchHistory(userId: string, params: GetUserMatchHistoryRequest): Promise<GetUserMatchHistoryResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/match/history/${encodeURIComponent(userId)}`, undefined, {query})
            return await resp.json() as GetUserMatchHistoryResponse
        }

        /**
         * Log a match result
         */
        public async logMatchResult(params: LogMatchResultRequest): Promise<LogMatchResultResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/match/log`, JSON.stringify(params))
            return await resp.json() as LogMatchResultResponse
        }
    }
}

export namespace notifications {
    export interface DeleteTokenRequest {
        userId: string
        token: string
    }

    export interface DeleteTokenResponse {
        success: boolean
        error?: string
    }

    export interface SaveTokenRequest {
        userId: string
        token: string
        deviceType?: string
    }

    export interface SaveTokenResponse {
        success: boolean
        error?: string
    }

    export interface SendNotificationRequest {
        title: string
        body: string
        targetType: "all" | "user" | "users"
        userId?: string
        targetUserIds?: string[]
        data?: { [key: string]: string }
        excludeUserId?: string
        deviceTypes?: string[]
    }

    export interface SendNotificationResponse {
        success: boolean
        sentCount: number
        failedCount: number
        error?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteToken = this.deleteToken.bind(this)
            this.saveToken = this.saveToken.bind(this)
            this.sendNotification = this.sendNotification.bind(this)
        }

        /**
         * Delete an FCM token (e.g. on logout)
         */
        public async deleteToken(params: DeleteTokenRequest): Promise<DeleteTokenResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                token:  params.token,
                userId: params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/notifications/token`, undefined, {query})
            return await resp.json() as DeleteTokenResponse
        }

        /**
         * Save or update FCM token for a user
         */
        public async saveToken(params: SaveTokenRequest): Promise<SaveTokenResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/notifications/token`, JSON.stringify(params))
            return await resp.json() as SaveTokenResponse
        }

        /**
         * Send notification to users
         */
        public async sendNotification(params: SendNotificationRequest): Promise<SendNotificationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/notifications/send`, JSON.stringify(params))
            return await resp.json() as SendNotificationResponse
        }
    }
}

export namespace progress {
    export interface CompleteLevelRequest {
        userId: string
        levelId: number
    }

    export interface CompleteLevelResponse {
        success: boolean
        progress?: LevelProgress
        levelId?: number
        alreadyCompleted?: boolean
        error?: string
    }

    export interface CompletedLevel {
        "level_id": number
        "completed_at": string
    }

    export interface GetCompletedLevelsRequest {
        limit?: number
        offset?: number
    }

    export interface GetCompletedLevelsResponse {
        success: boolean
        levels?: CompletedLevel[]
        error?: string
    }

    export interface GetLevelProgressResponse {
        success: boolean
        progress?: LevelProgress
        completedCount?: number
        error?: string
    }

    export interface IsLevelCompletedResponse {
        success: boolean
        completed?: boolean
        completedAt?: string | null
        error?: string
    }

    export interface LevelProgress {
        id: string
        "user_id": string
        "current_level": number
        "created_at": string
    }

    export interface ResetLevelProgressResponse {
        success: boolean
        deletedLevels?: number
        error?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.completeLevel = this.completeLevel.bind(this)
            this.getCompletedLevels = this.getCompletedLevels.bind(this)
            this.getLevelProgress = this.getLevelProgress.bind(this)
            this.isLevelCompleted = this.isLevelCompleted.bind(this)
            this.resetLevelProgress = this.resetLevelProgress.bind(this)
        }

        /**
         * Complete a level
         */
        public async completeLevel(params: CompleteLevelRequest): Promise<CompleteLevelResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/progress/complete`, JSON.stringify(params))
            return await resp.json() as CompleteLevelResponse
        }

        /**
         * Get completed levels
         */
        public async getCompletedLevels(userId: string, params: GetCompletedLevelsRequest): Promise<GetCompletedLevelsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/progress/completed/${encodeURIComponent(userId)}`, undefined, {query})
            return await resp.json() as GetCompletedLevelsResponse
        }

        /**
         * Get level progress
         */
        public async getLevelProgress(userId: string): Promise<GetLevelProgressResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/progress/${encodeURIComponent(userId)}`)
            return await resp.json() as GetLevelProgressResponse
        }

        /**
         * Check if level is completed
         */
        public async isLevelCompleted(userId: string, levelId: number): Promise<IsLevelCompletedResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/progress/check/${encodeURIComponent(userId)}/${encodeURIComponent(levelId)}`)
            return await resp.json() as IsLevelCompletedResponse
        }

        /**
         * Reset level progress
         */
        public async resetLevelProgress(userId: string): Promise<ResetLevelProgressResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/progress/reset/${encodeURIComponent(userId)}`)
            return await resp.json() as ResetLevelProgressResponse
        }
    }
}

export namespace stars {
    export interface AddStarsRequest {
        userId: string
        amount: number
    }

    export interface AddStarsResponse {
        success: boolean
        data?: UserStars
        error?: string
    }

    export interface CanClaimDailyRewardResponse {
        success: boolean
        canClaim?: boolean
        lastClaim?: string | null
        error?: string
    }

    export interface ClaimDailyRewardRequest {
        userId: string
    }

    export interface ClaimDailyRewardResponse {
        success: boolean
        data?: UserStars
        reward?: number
        newStreak?: number
        error?: string
    }

    export interface GetUserStarsResponse {
        success: boolean
        data?: UserStars
        error?: string
    }

    export interface RemoveStarsRequest {
        userId: string
        amount: number
    }

    export interface RemoveStarsResponse {
        success: boolean
        data?: UserStars
        error?: string
    }

    export interface UserStars {
        id: string
        "user_id": string
        stars: number
        "last_daily_claim": string | null
        "daily_streak": number
        "created_at": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addStars = this.addStars.bind(this)
            this.canClaimDailyReward = this.canClaimDailyReward.bind(this)
            this.claimDailyReward = this.claimDailyReward.bind(this)
            this.getUserStars = this.getUserStars.bind(this)
            this.removeStars = this.removeStars.bind(this)
        }

        /**
         * Add stars to user
         */
        public async addStars(params: AddStarsRequest): Promise<AddStarsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/stars/add`, JSON.stringify(params))
            return await resp.json() as AddStarsResponse
        }

        /**
         * Check if daily reward can be claimed
         */
        public async canClaimDailyReward(userId: string): Promise<CanClaimDailyRewardResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/stars/daily/check/${encodeURIComponent(userId)}`)
            return await resp.json() as CanClaimDailyRewardResponse
        }

        /**
         * Claim daily reward
         */
        public async claimDailyReward(params: ClaimDailyRewardRequest): Promise<ClaimDailyRewardResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/stars/daily/claim`, JSON.stringify(params))
            return await resp.json() as ClaimDailyRewardResponse
        }

        /**
         * Get user stars balance
         */
        public async getUserStars(userId: string): Promise<GetUserStarsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/stars/${encodeURIComponent(userId)}`)
            return await resp.json() as GetUserStarsResponse
        }

        /**
         * Remove stars from user
         */
        public async removeStars(params: RemoveStarsRequest): Promise<RemoveStarsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/stars/remove`, JSON.stringify(params))
            return await resp.json() as RemoveStarsResponse
        }
    }
}

export namespace trophies {
    export interface AddTrophiesRequest {
        userId: string
        amount: number
    }

    export interface AddTrophiesResponse {
        success: boolean
        data?: UserTrophies
        error?: string
    }

    export interface ApplyMatchResultRequest {
        userId: string
        result: MatchResult
        trophyChange?: number
    }

    export interface ApplyMatchResultResponse {
        success: boolean
        data?: UserTrophies
        trophyChange?: number
        error?: string
    }

    export interface GetLeaderboardRequest {
        limit?: number
        offset?: number
    }

    export interface GetLeaderboardResponse {
        success: boolean
        leaderboard?: LeaderboardEntry[]
        error?: string
    }

    export interface GetUserTrophiesResponse {
        success: boolean
        data?: UserTrophies
        error?: string
    }

    export interface LeaderboardEntry {
        "user_id": string
        name: string | null
        username: string | null
        avatar: string | null
        trophies: number
        wins: number
        losses: number
        rank: number
        "player_type": "user" | "bot"
    }

    export type MatchResult = "win" | "lose" | "draw"

    export interface UserTrophies {
        id: string
        "user_id": string
        trophies: number
        "highest_trophies": number
        wins: number
        losses: number
        draws: number
        "created_at": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addTrophies = this.addTrophies.bind(this)
            this.applyMatchResult = this.applyMatchResult.bind(this)
            this.getLeaderboard = this.getLeaderboard.bind(this)
            this.getUserTrophies = this.getUserTrophies.bind(this)
        }

        /**
         * Add/remove trophies
         */
        public async addTrophies(params: AddTrophiesRequest): Promise<AddTrophiesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/trophies/add`, JSON.stringify(params))
            return await resp.json() as AddTrophiesResponse
        }

        /**
         * Apply match result
         */
        public async applyMatchResult(params: ApplyMatchResultRequest): Promise<ApplyMatchResultResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/trophies/match`, JSON.stringify(params))
            return await resp.json() as ApplyMatchResultResponse
        }

        /**
         * Get leaderboard
         */
        public async getLeaderboard(params: GetLeaderboardRequest): Promise<GetLeaderboardResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/leaderboard`, undefined, {query})
            return await resp.json() as GetLeaderboardResponse
        }

        /**
         * Get user trophies
         */
        public async getUserTrophies(userId: string): Promise<GetUserTrophiesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/trophies/${encodeURIComponent(userId)}`)
            return await resp.json() as GetUserTrophiesResponse
        }
    }
}

export namespace user {
    export interface CreateUserRequest {
        firebaseId: string
        deviceId?: string
        name?: string
        username?: string
        avatar?: string
    }

    export interface CreateUserResponse {
        success: boolean
        user?: User
        error?: string
    }

    export interface DeleteUserResponse {
        success: boolean
        error?: string
    }

    export interface GetAllUsersRequest {
        limit?: number
        offset?: number
    }

    export interface GetAllUsersResponse {
        success: boolean
        users?: User[]
        error?: string
    }

    export interface GetUserByFirebaseIdResponse {
        success: boolean
        user?: User
        error?: string
    }

    export interface GetUserResponse {
        success: boolean
        user?: User
        error?: string
    }

    export interface UpdateUserRequest {
        deviceId?: string
        name?: string
        username?: string
        avatar?: string
    }

    export interface UpdateUserResponse {
        success: boolean
        user?: User
        error?: string
    }

    export interface User {
        id: string
        "firebase_id": string
        "device_id": string | null
        name: string | null
        username: string | null
        avatar: string | null
        "created_at": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createUser = this.createUser.bind(this)
            this.deleteUser = this.deleteUser.bind(this)
            this.getAllUsers = this.getAllUsers.bind(this)
            this.getUser = this.getUser.bind(this)
            this.getUserByFirebaseId = this.getUserByFirebaseId.bind(this)
            this.updateUser = this.updateUser.bind(this)
        }

        /**
         * Create a new user
         */
        public async createUser(params: CreateUserRequest): Promise<CreateUserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/user`, JSON.stringify(params))
            return await resp.json() as CreateUserResponse
        }

        /**
         * Delete a user
         */
        public async deleteUser(userId: string): Promise<DeleteUserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/user/${encodeURIComponent(userId)}`)
            return await resp.json() as DeleteUserResponse
        }

        /**
         * Get all users
         */
        public async getAllUsers(params: GetAllUsersRequest): Promise<GetAllUsersResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/user/all`, undefined, {query})
            return await resp.json() as GetAllUsersResponse
        }

        /**
         * Get a user by ID
         */
        public async getUser(userId: string): Promise<GetUserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/user/${encodeURIComponent(userId)}`)
            return await resp.json() as GetUserResponse
        }

        /**
         * Get a user by Firebase ID
         */
        public async getUserByFirebaseId(firebaseId: string): Promise<GetUserByFirebaseIdResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/user/firebase/${encodeURIComponent(firebaseId)}`)
            return await resp.json() as GetUserByFirebaseIdResponse
        }

        /**
         * Update a user
         */
        public async updateUser(userId: string, params: UpdateUserRequest): Promise<UpdateUserResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/user/${encodeURIComponent(userId)}`, JSON.stringify(params))
            return await resp.json() as UpdateUserResponse
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "everydle-qnxi-Generated-TS-Client (Encore/v1.53.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
